### ISSUE TITLE
A quetion

### ISSUE THREAD

**Issue by Moonlightxb** [hiroki13/instance-based-ner#3]
Gook work！But I can't find convert_conll03_to_json.py and retrieve_knn_sents_with_glove.py which are included by create_ datasets.sh In all code files.Could you tell me how to get it?

**Comment by hiroki13** [comment]
Thank you for having interest in our code!!
I have uploaded the files.

**Comment by Moonlightxb** [comment]
Thank very mach for your help！



---Original---
