### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Moonlightxb** [hiroki13/instance-based-ner#4]
Good work,but I couldn't get valid.json in checkpoint_knn_conll2003_lstm-minus_batch8_keep07_0 which I follow your README to download in https://drive.google.com/open?id=1d_KzED0UKEVnorymxiylzEOHpXoFF8TN when I run python train_knn_models.py --config_file data/config/config.knn.conll2003.json .I find there is train.json but not valid.json but there is "valid_set": "data/dataset/conll2003_knn/valid.json" in data/config/config.knn.conll2003.json.Could you tell me how to get the valid.json?The vaild.json I mentioned is ued for pretrained model,Isn't it?

**Comment by hiroki13** [comment]
Thank you for having interest in our code!!
https://github.com/hiroki13/instance-based-ner/blob/master/create_datasets.sh (Line 13) indicates how to create valid.json.
Please check it.

**Comment by Moonlightxb** [comment]
> 感谢您对我们的代码感兴趣！！
> https://github.com/hiroki13/instance-based-ner/blob/master/create_datasets.sh（第13行）指示如何创建有效的.json。
> 请检查一下。

I konw what you mean.But I encountered a error when I run "python train_knn_models.py --config_file data/config/config.knn.conll2003.json" if I use the valid.json and train.json which I get from running "create_datasets.sh".
 The error is
   self.n_gold_spans = count_gold_spans(valid_path)
  File "D:\instance-based-ner\utils\data_utils.py", line 39, in count_gold_spans
    n_gold_spans += len(record["tags"])
KeyError: 'tags'
According to this error,I think 
"train_set": "data/dataset/conll2003_knn/train.json","valid_set": "data/dataset/conll2003_knn/valid.json", which in /config/config.knn.conll2003.json means there is "tags" in the valid.json and the train.json.But the train.json and valid.json which I get from running "create_datasets.sh" has no "tags".

**Comment by Moonlightxb** [comment]
> Thank you for having interest in our code!!
> https://github.com/hiroki13/instance-based-ner/blob/master/create_datasets.sh (Line 13) indicates how to create valid.json.
> Please check it.

I konw the reason why I get the error.Thankyou very much.
